// Iron & Dominion 1914 - Config
const PIXELS_PER_DEGREE=100,MIN_ZOOM=0.08,MAX_ZOOM=30.0;
const STRATEGIC_ZOOM=0.8,TACTICAL_ZOOM=1.8;
const MAP_CENTER_LON=10,MAP_CENTER_LAT=50;
const OCEAN_COLOR_TOP="#1a4060",OCEAN_COLOR_BOTTOM="#2a5a7a";
const COUNTRY_COLORS = {"ALBANIA":"#E41E20","TURKEY":"#509E2F","AUSTRIA_HUNGARY":"#CFB990","BULGARIA":"#00966E","BELGIUM":"#FDDA24","DENMARK":"#E3000F","GERMANY":"#4A7B8C","RUSSIA":"#0039A6","FRANCE":"#3B5EAB","FINLAND":"#003580","NETHERLANDS":"#FF6600","MONTENEGRO":"#CE1126","LUXEMBOURG":"#00A1DE","ROMANIA":"#002B7F","NORWAY":"#BA0C2E","PORTUGAL":"#006600","SWEDEN":"#006AA7","SWITZERLAND":"#D52B1E","SERBIA":"#C6363C","SPAIN":"#F1BF00","GREECE":"#0D5EAF","ITALY":"#008C45","UK":"#C8102E"};
const COUNTRY_CN = {"ALBANIA":"阿尔巴尼亚","TURKEY":"奥斯曼帝国","AUSTRIA_HUNGARY":"奥匈帝国","BULGARIA":"保加利亚","BELGIUM":"比利时","DENMARK":"丹麦","GERMANY":"德国","RUSSIA":"俄国","FRANCE":"法国","FINLAND":"芬兰","NETHERLANDS":"荷兰","MONTENEGRO":"黑山","LUXEMBOURG":"卢森堡","ROMANIA":"罗马尼亚","NORWAY":"挪威","PORTUGAL":"葡萄牙","SWEDEN":"瑞典","SWITZERLAND":"瑞士","SERBIA":"塞尔维亚","SPAIN":"西班牙","GREECE":"希腊","ITALY":"意大利","UK":"英国"};
const TERRAIN_CN={"flat": "平原", "hills": "丘陵", "mountains": "山地", "urban": "都市"};
const BORDER_COLOR="rgba(255,255,255,0.2)",BORDER_WIDTH=1.0;
const PROVINCE_BORDER_COLOR="rgba(255,255,255,0.12)",PROVINCE_BORDER_WIDTH=0.5;
const CITY_DOT_RADIUS=3,CAPITAL_DOT_RADIUS=5;
const CITY_DOT_COLOR="#f0e6d3",CAPITAL_DOT_COLOR="#ffd700";
const CITY_NAME_COLOR="#e8e0d0",PORT_NAME_COLOR="#7ab8d4";
const CITY_NAME_FONT="11px \"Segoe UI\",sans-serif";
const CAPITAL_NAME_FONT="bold 12px \"Segoe UI\",sans-serif";
const ECONOMY_INTERVAL=30000,FACTORY_COST=50,FACTORY_BUILD_TIME=10,MAINTENANCE_COST=1.5;
const ZOOM_SPEED=0.15,PAN_SPEED=1,TOP_BAR_HEIGHT=40,BOTTOM_BAR_HEIGHT=48,BOTTOM_TAB_BAR_HEIGHT=36,TAB_PANEL_HEIGHT=350;
// 列强：不可被吞并或附属
const GREAT_POWERS = ['UK','FRANCE','GERMANY','AUSTRIA_HUNGARY','ITALY','RUSSIA'];
function isGreatPower(c) { return GREAT_POWERS.includes(c); }
// 附属国体系: VASSAL_OF[vassalCountry] = suzerainCountry
// 宗主国可在附属国领土自由行军；附属国20%收入上交宗主国
const VASSAL_OF = { FINLAND: 'RUSSIA' };
