// ============================================================
//  Iron & Dominion 1914 — 城市数据
// ============================================================

const CITIES = [
    { id:'berlin', name:'柏林', country:'GERMANY', lon:13.41, lat:52.52, isCapital:true },
    { id:'hamburg', name:'汉堡', country:'GERMANY', lon:9.99, lat:53.55, isCapital:false },
    { id:'munich', name:'慕尼黑', country:'GERMANY', lon:11.58, lat:48.14, isCapital:false },
    { id:'cologne', name:'科隆', country:'GERMANY', lon:6.96, lat:50.94, isCapital:false },
    { id:'frankfurt', name:'法兰克福', country:'GERMANY', lon:8.68, lat:50.11, isCapital:false },
    { id:'leipzig', name:'莱比锡', country:'GERMANY', lon:12.37, lat:51.34, isCapital:false },
    { id:'stuttgart', name:'斯图加特', country:'GERMANY', lon:9.18, lat:48.78, isCapital:false },
    { id:'dresden', name:'德累斯顿', country:'GERMANY', lon:13.74, lat:51.05, isCapital:false },
    { id:'nuremberg', name:'纽伦堡', country:'GERMANY', lon:11.08, lat:49.45, isCapital:false },
    { id:'bremen', name:'不来梅', country:'GERMANY', lon:8.80, lat:53.08, isCapital:false },
    { id:'kiel', name:'基尔', country:'GERMANY', lon:10.14, lat:54.32, isCapital:false },
    { id:'danzig', name:'但泽', country:'GERMANY', lon:18.65, lat:54.35, isCapital:false },
    { id:'metz', name:'梅斯', country:'GERMANY', lon:6.18, lat:49.12, isCapital:false },
    { id:'posen', name:'波森', country:'GERMANY', lon:16.92, lat:52.41, isCapital:false },
    { id:'stettin', name:'斯德丁', country:'GERMANY', lon:14.55, lat:53.43, isCapital:false },
    { id:'konigsberg', name:'柯尼斯堡', country:'GERMANY', lon:20.51, lat:54.71, isCapital:false },
    { id:'wilhelmshaven', name:'威廉港', country:'GERMANY', lon:8.12, lat:53.52, isCapital:false },
    { id:'hannover', name:'汉诺威', country:'GERMANY', lon:9.73, lat:52.37, isCapital:false },
    { id:'dortmund', name:'多特蒙德', country:'GERMANY', lon:7.47, lat:51.51, isCapital:false },
    { id:'aachen', name:'亚琛', country:'GERMANY', lon:6.08, lat:50.78, isCapital:false },
    { id:'trier', name:'特里尔', country:'GERMANY', lon:6.64, lat:49.75, isCapital:false },
    { id:'koblenz', name:'科布伦茨', country:'GERMANY', lon:7.61, lat:50.36, isCapital:false },
    { id:'karlsruhe', name:'卡尔斯鲁厄', country:'GERMANY', lon:8.40, lat:49.01, isCapital:false },
    { id:'mannheim', name:'曼海姆', country:'GERMANY', lon:8.47, lat:49.49, isCapital:false },
    { id:'saarbruecken', name:'萨尔布吕肯', country:'GERMANY', lon:6.99, lat:49.23, isCapital:false },
    { id:'mainz', name:'美因茨', country:'GERMANY', lon:8.27, lat:49.99, isCapital:false },
    { id:'strasbourg', name:'斯特拉斯堡', country:'GERMANY', lon:7.75, lat:48.58, isCapital:false },
    { id:'paris', name:'巴黎', country:'FRANCE', lon:2.35, lat:48.86, isCapital:true },
    { id:'marseille', name:'马赛', country:'FRANCE', lon:5.37, lat:43.30, isCapital:false },
    { id:'lyon', name:'里昂', country:'FRANCE', lon:4.84, lat:45.76, isCapital:false },
    { id:'bordeaux', name:'波尔多', country:'FRANCE', lon:-0.58, lat:44.84, isCapital:false },
    { id:'lille', name:'里尔', country:'FRANCE', lon:3.06, lat:50.63, isCapital:false },
    { id:'brest', name:'布雷斯特', country:'FRANCE', lon:-4.49, lat:48.39, isCapital:false },
    { id:'toulon', name:'土伦', country:'FRANCE', lon:5.93, lat:43.12, isCapital:false },
    { id:'nantes', name:'南特', country:'FRANCE', lon:-1.55, lat:47.22, isCapital:false },
    { id:'toulouse', name:'图卢兹', country:'FRANCE', lon:1.44, lat:43.60, isCapital:false },
    { id:'amiens', name:'亚眠', country:'FRANCE', lon:2.30, lat:49.89, isCapital:false },
    { id:'reims', name:'兰斯', country:'FRANCE', lon:4.03, lat:49.26, isCapital:false },
    { id:'rouen', name:'鲁昂', country:'FRANCE', lon:1.09, lat:49.44, isCapital:false },
    { id:'dijon', name:'第戎', country:'FRANCE', lon:5.04, lat:47.32, isCapital:false },
    { id:'nice', name:'尼斯', country:'FRANCE', lon:7.27, lat:43.71, isCapital:false },
    { id:'tours', name:'图尔', country:'FRANCE', lon:0.69, lat:47.39, isCapital:false },
    { id:'montpellier', name:'蒙彼利埃', country:'FRANCE', lon:3.88, lat:43.61, isCapital:false },
    { id:'verdun', name:'凡尔登', country:'FRANCE', lon:5.38, lat:49.16, isCapital:false },
    { id:'soissons', name:'苏瓦松', country:'FRANCE', lon:3.33, lat:49.38, isCapital:false },
    { id:'laon', name:'拉昂', country:'FRANCE', lon:3.62, lat:49.56, isCapital:false },
    { id:'compiegne', name:'贡比涅', country:'FRANCE', lon:2.83, lat:49.42, isCapital:false },
    { id:'epernay', name:'埃佩尔奈', country:'FRANCE', lon:3.95, lat:49.04, isCapital:false },
    { id:'chalons', name:'沙隆', country:'FRANCE', lon:4.00, lat:48.95, isCapital:false },
    { id:'epinal', name:'埃皮纳勒', country:'FRANCE', lon:6.45, lat:48.17, isCapital:false },
    { id:'belfort', name:'贝尔福', country:'FRANCE', lon:6.86, lat:47.64, isCapital:false },
    { id:'nancy', name:'南锡', country:'FRANCE', lon:6.18, lat:48.69, isCapital:false },
    { id:'toul', name:'图勒', country:'FRANCE', lon:5.89, lat:48.68, isCapital:false },
    { id:'sedan', name:'色当', country:'FRANCE', lon:4.94, lat:49.70, isCapital:false },
    { id:'mezieres', name:'梅济耶尔', country:'FRANCE', lon:4.72, lat:49.77, isCapital:false },
    { id:'barleduc', name:'巴勒迪克', country:'FRANCE', lon:5.16, lat:48.77, isCapital:false },
    { id:'colmar', name:'科尔马', country:'FRANCE', lon:7.36, lat:48.08, isCapital:false },
    { id:'boulogne', name:'布洛涅', country:'FRANCE', lon:1.61, lat:50.73, isCapital:false },
    { id:'dieppe', name:'迪耶普', country:'FRANCE', lon:1.08, lat:49.93, isCapital:false },
    { id:'cherbourg', name:'瑟堡', country:'FRANCE', lon:-1.62, lat:49.64, isCapital:false },
    { id:'st_nazaire', name:'圣纳泽尔', country:'FRANCE', lon:-2.20, lat:47.28, isCapital:false },
    { id:'london', name:'伦敦', country:'UK', lon:-0.13, lat:51.51, isCapital:true },
    { id:'edinburgh', name:'爱丁堡', country:'UK', lon:-3.19, lat:55.95, isCapital:false },
    { id:'glasgow', name:'格拉斯哥', country:'UK', lon:-4.25, lat:55.86, isCapital:false },
    { id:'liverpool', name:'利物浦', country:'UK', lon:-2.98, lat:53.41, isCapital:false },
    { id:'manchester', name:'曼彻斯特', country:'UK', lon:-2.24, lat:53.48, isCapital:false },
    { id:'leeds', name:'利兹', country:'UK', lon:-1.55, lat:53.80, isCapital:false },
    { id:'birmingham', name:'伯明翰', country:'UK', lon:-1.89, lat:52.49, isCapital:false },
    { id:'southampton', name:'南安普顿', country:'UK', lon:-1.40, lat:50.91, isCapital:false },
    { id:'dover', name:'多佛', country:'UK', lon:1.32, lat:51.13, isCapital:false },
    { id:'portsmouth', name:'朴茨茅斯', country:'UK', lon:-1.09, lat:50.82, isCapital:false },
    { id:'hull', name:'赫尔', country:'UK', lon:-0.33, lat:53.75, isCapital:false },
    { id:'bristol', name:'布里斯托尔', country:'UK', lon:-2.59, lat:51.45, isCapital:false },
    { id:'norwich', name:'诺里奇', country:'UK', lon:1.30, lat:52.63, isCapital:false },
    { id:'plymouth', name:'普利茅斯', country:'UK', lon:-4.14, lat:50.37, isCapital:false },
    { id:'aberdeen', name:'阿伯丁', country:'UK', lon:-2.10, lat:57.15, isCapital:false },
    { id:'scapa', name:'斯卡帕湾', country:'UK', lon:-3.10, lat:58.90, isCapital:false },
    { id:'belfast', name:'贝尔法斯特', country:'UK', lon:-5.93, lat:54.60, isCapital:false },
    { id:'cardiff', name:'加的夫', country:'UK', lon:-3.18, lat:51.48, isCapital:false },
    { id:'york', name:'约克', country:'UK', lon:-1.08, lat:53.96, isCapital:false },
    { id:'dublin', name:'都柏林', country:'UK', lon:-6.27, lat:53.35 },
    { id:'cork', name:'科克', country:'UK', lon:-8.47, lat:51.90, isCapital:false },
    { id:'galway', name:'戈尔韦', country:'UK', lon:-9.05, lat:53.27, isCapital:false },
    { id:'limerick', name:'利默里克', country:'UK', lon:-8.63, lat:52.67, isCapital:false },
    { id:'waterford', name:'沃特福德', country:'UK', lon:-7.11, lat:52.26, isCapital:false },
    { id:'rome', name:'罗马', country:'ITALY', lon:12.50, lat:41.90, isCapital:true },
    { id:'milan', name:'米兰', country:'ITALY', lon:9.19, lat:45.46, isCapital:false },
    { id:'naples', name:'那不勒斯', country:'ITALY', lon:14.27, lat:40.85, isCapital:false },
    { id:'turin', name:'都灵', country:'ITALY', lon:7.69, lat:45.07, isCapital:false },
    { id:'venice', name:'威尼斯', country:'ITALY', lon:12.32, lat:45.44, isCapital:false },
    { id:'genoa', name:'热那亚', country:'ITALY', lon:8.93, lat:44.41, isCapital:false },
    { id:'florence', name:'佛罗伦萨', country:'ITALY', lon:11.26, lat:43.77, isCapital:false },
    { id:'palermo', name:'巴勒莫', country:'ITALY', lon:13.36, lat:38.12, isCapital:false },
    { id:'bologna', name:'博洛尼亚', country:'ITALY', lon:11.34, lat:44.50, isCapital:false },
    { id:'trieste', name:'的里雅斯特', country:'ITALY', lon:13.77, lat:45.65, isCapital:false },
    { id:'verona', name:'维罗纳', country:'ITALY', lon:10.99, lat:45.44, isCapital:false },
    { id:'bari', name:'巴里', country:'ITALY', lon:16.87, lat:41.12, isCapital:false },
    { id:'taranto', name:'塔兰托', country:'ITALY', lon:17.25, lat:40.48, isCapital:false },
    { id:'catania', name:'卡塔尼亚', country:'ITALY', lon:15.09, lat:37.50, isCapital:false },
    { id:'cagliari', name:'卡利亚里', country:'ITALY', lon:9.11, lat:39.22, isCapital:false },
    { id:'ancona', name:'安科纳', country:'ITALY', lon:13.52, lat:43.62, isCapital:false },
    { id:'gorizia', name:'戈里齐亚', country:'ITALY', lon:13.62, lat:45.94, isCapital:false },
    { id:'padua', name:'帕多瓦', country:'ITALY', lon:11.88, lat:45.41, isCapital:false },
    { id:'udine', name:'乌迪内', country:'ITALY', lon:13.24, lat:46.06, isCapital:false },
    { id:'madrid', name:'马德里', country:'SPAIN', lon:-3.70, lat:40.42, isCapital:true },
    { id:'barcelona', name:'巴塞罗那', country:'SPAIN', lon:2.17, lat:41.39, isCapital:false },
    { id:'seville', name:'塞维利亚', country:'SPAIN', lon:-5.98, lat:37.39, isCapital:false },
    { id:'bilbao', name:'毕尔巴鄂', country:'SPAIN', lon:-2.93, lat:43.26, isCapital:false },
    { id:'valencia_sp', name:'瓦伦西亚', country:'SPAIN', lon:-0.38, lat:39.47, isCapital:false },
    { id:'malaga', name:'马拉加', country:'SPAIN', lon:-4.42, lat:36.72, isCapital:false },
    { id:'zaragoza', name:'萨拉戈萨', country:'SPAIN', lon:-0.88, lat:41.65, isCapital:false },
    { id:'san_sebastian', name:'圣塞巴斯蒂安', country:'SPAIN', lon:-1.98, lat:43.32, isCapital:false },
    { id:'lisbon', name:'里斯本', country:'PORTUGAL', lon:-9.14, lat:38.72, isCapital:true },
    { id:'porto', name:'波尔图', country:'PORTUGAL', lon:-8.68, lat:41.15, isCapital:false },
    { id:'faro', name:'法鲁', country:'PORTUGAL', lon:-7.93, lat:37.02, isCapital:false },
    { id:'coimbra', name:'科英布拉', country:'PORTUGAL', lon:-8.43, lat:40.21, isCapital:false },
    { id:'amsterdam', name:'阿姆斯特丹', country:'NETHERLANDS', lon:4.90, lat:52.37, isCapital:true },
    { id:'rotterdam', name:'鹿特丹', country:'NETHERLANDS', lon:4.48, lat:51.92, isCapital:false },
    { id:'thehague', name:'海牙', country:'NETHERLANDS', lon:4.30, lat:52.08, isCapital:false },
    { id:'utrecht', name:'乌得勒支', country:'NETHERLANDS', lon:5.12, lat:52.09, isCapital:false },
    { id:'groningen', name:'格罗宁根', country:'NETHERLANDS', lon:6.57, lat:53.22, isCapital:false },
    { id:'maastricht', name:'马斯特里赫特', country:'NETHERLANDS', lon:5.69, lat:50.85, isCapital:false },
    { id:'brussels', name:'布鲁塞尔', country:'BELGIUM', lon:4.35, lat:50.85, isCapital:true },
    { id:'antwerp', name:'安特卫普', country:'BELGIUM', lon:4.40, lat:51.22, isCapital:false },
    { id:'bruges', name:'布鲁日', country:'BELGIUM', lon:3.22, lat:51.21, isCapital:false },
    { id:'ostend', name:'奥斯坦德', country:'BELGIUM', lon:2.93, lat:51.23, isCapital:false },
    { id:'ypres', name:'伊普尔', country:'BELGIUM', lon:2.89, lat:50.85, isCapital:false },
    { id:'mons', name:'蒙斯', country:'BELGIUM', lon:3.95, lat:50.45, isCapital:false },
    { id:'charleroi', name:'沙勒罗瓦', country:'BELGIUM', lon:4.44, lat:50.41, isCapital:false },
    { id:'namur', name:'那慕尔', country:'BELGIUM', lon:4.86, lat:50.46, isCapital:false },
    { id:'liege', name:'列日', country:'BELGIUM', lon:5.57, lat:50.63, isCapital:false },
    { id:'bern', name:'伯尔尼', country:'SWITZERLAND', lon:7.45, lat:46.95, isCapital:true },
    { id:'zurich', name:'苏黎世', country:'SWITZERLAND', lon:8.54, lat:47.38, isCapital:false },
    { id:'geneva', name:'日内瓦', country:'SWITZERLAND', lon:6.14, lat:46.20, isCapital:false },
    { id:'basel', name:'巴塞尔', country:'SWITZERLAND', lon:7.59, lat:47.56, isCapital:false },
    { id:'lucerne', name:'卢塞恩', country:'SWITZERLAND', lon:8.31, lat:47.05, isCapital:false },
    { id:'lausanne', name:'洛桑', country:'SWITZERLAND', lon:6.63, lat:46.52, isCapital:false },
    { id:'copenhagen', name:'哥本哈根', country:'DENMARK', lon:12.57, lat:55.68, isCapital:true },
    { id:'aarhus', name:'奥胡斯', country:'DENMARK', lon:10.21, lat:56.16, isCapital:false },
    { id:'odense', name:'欧登塞', country:'DENMARK', lon:10.39, lat:55.40, isCapital:false },
    { id:'aalborg', name:'奥尔堡', country:'DENMARK', lon:9.92, lat:57.05, isCapital:false },
    { id:'luxembourg', name:'卢森堡市', country:'LUXEMBOURG', lon:6.13, lat:49.61, isCapital:true },
    { id:'vienna', name:'维也纳', country:'AUSTRIA_HUNGARY', lon:16.37, lat:48.21, isCapital:true },
    { id:'budapest', name:'布达佩斯', country:'AUSTRIA_HUNGARY', lon:19.04, lat:47.50, isCapital:false },
    { id:'prague', name:'布拉格', country:'AUSTRIA_HUNGARY', lon:14.42, lat:50.08, isCapital:false },
    { id:'zagreb', name:'萨格勒布', country:'AUSTRIA_HUNGARY', lon:15.98, lat:45.82, isCapital:false },
    { id:'sarajevo', name:'萨拉热窝', country:'AUSTRIA_HUNGARY', lon:18.41, lat:43.85, isCapital:false },
    { id:'krakow', name:'克拉科夫', country:'AUSTRIA_HUNGARY', lon:19.94, lat:50.06, isCapital:false },
    { id:'bratislava', name:'布拉迪斯拉发', country:'AUSTRIA_HUNGARY', lon:17.11, lat:48.15, isCapital:false },
    { id:'graz', name:'格拉茨', country:'AUSTRIA_HUNGARY', lon:15.44, lat:47.07, isCapital:false },
    { id:'linz', name:'林茨', country:'AUSTRIA_HUNGARY', lon:14.29, lat:48.31, isCapital:false },
    { id:'salzburg_ah', name:'萨尔茨堡', country:'AUSTRIA_HUNGARY', lon:13.05, lat:47.81, isCapital:false },
    { id:'lemberg', name:'伦贝格(利沃夫)', country:'AUSTRIA_HUNGARY', lon:24.03, lat:49.84, isCapital:false },
    { id:'cattaro', name:'卡塔罗', country:'AUSTRIA_HUNGARY', lon:18.77, lat:42.43, isCapital:false },
    { id:'spalato', name:'斯帕拉托', country:'AUSTRIA_HUNGARY', lon:16.44, lat:43.51, isCapital:false },
    { id:'belgrade', name:'贝尔格莱德', country:'SERBIA', lon:20.46, lat:43.82, isCapital:true },
    { id:'nis', name:'尼什', country:'SERBIA', lon:21.90, lat:43.32, isCapital:false },
    { id:'kragujevac', name:'克拉古耶瓦茨', country:'SERBIA', lon:20.69, lat:44.01, isCapital:false },
    { id:'podgorica', name:'波德戈里察', country:'MONTENEGRO', lon:19.26, lat:42.44, isCapital:true },
    { id:'cetinje', name:'采蒂涅', country:'MONTENEGRO', lon:18.92, lat:42.39, isCapital:false },
    { id:'bar_mn', name:'巴尔', country:'MONTENEGRO', lon:19.10, lat:42.10, isCapital:false },
    { id:'sofia', name:'索非亚', country:'BULGARIA', lon:23.32, lat:42.70, isCapital:true },
    { id:'plovdiv', name:'普罗夫迪夫', country:'BULGARIA', lon:24.75, lat:42.15, isCapital:false },
    { id:'varna', name:'瓦尔纳', country:'BULGARIA', lon:27.91, lat:43.22, isCapital:false },
    { id:'burgas', name:'布尔加斯', country:'BULGARIA', lon:27.47, lat:42.51, isCapital:false },
    { id:'ruse', name:'鲁塞', country:'BULGARIA', lon:25.97, lat:43.83, isCapital:false },
    { id:'pleven', name:'普列文', country:'BULGARIA', lon:24.62, lat:43.42, isCapital:false },
    { id:'bucharest', name:'布加勒斯特', country:'ROMANIA', lon:26.10, lat:44.43, isCapital:true },
    { id:'cluj', name:'克卢日', country:'ROMANIA', lon:23.60, lat:46.77, isCapital:false },
    { id:'timisoara', name:'蒂米什瓦拉', country:'ROMANIA', lon:21.23, lat:45.75, isCapital:false },
    { id:'iasi', name:'雅西', country:'ROMANIA', lon:27.59, lat:47.16, isCapital:false },
    { id:'constanta', name:'康斯坦察', country:'ROMANIA', lon:28.63, lat:44.18, isCapital:false },
    { id:'brasov', name:'布拉索夫', country:'ROMANIA', lon:25.60, lat:45.65, isCapital:false },
    { id:'galati', name:'加拉茨', country:'ROMANIA', lon:28.04, lat:45.43, isCapital:false },
    { id:'craiova', name:'克拉约瓦', country:'ROMANIA', lon:23.80, lat:44.32, isCapital:false },
    { id:'athens', name:'雅典', country:'GREECE', lon:23.73, lat:37.98, isCapital:true },
    { id:'thessaloniki', name:'塞萨洛尼基', country:'GREECE', lon:22.94, lat:40.64, isCapital:false },
    { id:'patras', name:'帕特雷', country:'GREECE', lon:21.73, lat:38.25, isCapital:false },
    { id:'heraklion', name:'伊拉克利翁', country:'GREECE', lon:25.13, lat:35.34, isCapital:false },
    { id:'corfu', name:'科孚', country:'GREECE', lon:19.92, lat:39.62, isCapital:false },
    { id:'tirana', name:'地拉那', country:'ALBANIA', lon:19.82, lat:41.33, isCapital:true },
    { id:'durres', name:'都拉斯', country:'ALBANIA', lon:19.44, lat:41.32, isCapital:false },
    { id:'valona', name:'发罗拉', country:'ALBANIA', lon:19.49, lat:40.47, isCapital:false },
    { id:'istanbul', name:'伊斯坦布尔', country:'TURKEY', lon:28.98, lat:41.01, isCapital:true },
    { id:'ankara', name:'安卡拉', country:'TURKEY', lon:32.86, lat:39.93, isCapital:false },
    { id:'izmir', name:'伊兹密尔', country:'TURKEY', lon:27.14, lat:38.42, isCapital:false },
    { id:'adrianople', name:'阿德里安堡', country:'TURKEY', lon:26.56, lat:41.68, isCapital:false },
    { id:'trebizond', name:'特拉布宗', country:'TURKEY', lon:39.72, lat:41.00, isCapital:false },
    { id:'bursa', name:'布尔萨', country:'TURKEY', lon:29.06, lat:40.19, isCapital:false },
    { id:'konya', name:'科尼亚', country:'TURKEY', lon:32.50, lat:37.87, isCapital:false },
    { id:'sivas', name:'锡瓦斯', country:'TURKEY', lon:37.02, lat:39.75, isCapital:false },
    { id:'erzurum', name:'埃尔祖鲁姆', country:'TURKEY', lon:41.28, lat:39.91, isCapital:false },
    { id:'saint_petersburg', name:'圣彼得堡', country:'RUSSIA', lon:30.32, lat:59.93, isCapital:true },
    { id:'moscow', name:'莫斯科', country:'RUSSIA', lon:37.62, lat:55.75, isCapital:false },
    { id:'warsaw', name:'华沙', country:'RUSSIA', lon:21.01, lat:52.23, isCapital:false },
    { id:'kiev', name:'基辅', country:'RUSSIA', lon:30.52, lat:50.45, isCapital:false },
    { id:'odessa', name:'敖德萨', country:'RUSSIA', lon:30.73, lat:46.48, isCapital:false },
    { id:'riga', name:'里加', country:'RUSSIA', lon:24.11, lat:56.95, isCapital:false },
    { id:'minsk', name:'明斯克', country:'RUSSIA', lon:27.57, lat:53.90, isCapital:false },
    { id:'tula', name:'图拉', country:'RUSSIA', lon:37.62, lat:54.20, isCapital:false },
    { id:'sevastopol', name:'塞瓦斯托波尔', country:'RUSSIA', lon:33.53, lat:44.62, isCapital:false },
    { id:'tiflis', name:'梯弗里斯', country:'RUSSIA', lon:44.79, lat:41.71, isCapital:false },
    { id:'tsarskoje', name:'皇村', country:'RUSSIA', lon:30.42, lat:59.70, isCapital:false },
    { id:'samara', name:'萨马拉', country:'RUSSIA', lon:50.15, lat:53.20, isCapital:false },
    { id:'helsinkifi', name:'赫尔辛基', country:'FINLAND', lon:24.94, lat:60.17, isCapital:true },
    { id:'turku', name:'图尔库', country:'FINLAND', lon:22.27, lat:60.45, isCapital:false },
    { id:'tampere', name:'坦佩雷', country:'FINLAND', lon:23.76, lat:61.50, isCapital:false },
    { id:'viipuri', name:'维堡', country:'FINLAND', lon:28.75, lat:60.71, isCapital:false },
    { id:'vaasa', name:'瓦萨', country:'FINLAND', lon:21.63, lat:63.10, isCapital:false },
    { id:'oulu', name:'奥卢', country:'FINLAND', lon:25.47, lat:65.01, isCapital:false },
    { id:'oslo', name:'奥斯陆', country:'NORWAY', lon:10.75, lat:59.91, isCapital:true },
    { id:'bergen', name:'卑尔根', country:'NORWAY', lon:5.32, lat:60.39, isCapital:false },
    { id:'trondheim', name:'特隆赫姆', country:'NORWAY', lon:10.39, lat:63.44, isCapital:false },
    { id:'narvik', name:'纳尔维克', country:'NORWAY', lon:17.43, lat:68.43, isCapital:false },
    { id:'tromso', name:'特罗姆瑟', country:'NORWAY', lon:18.96, lat:69.65, isCapital:false },
    { id:'stavanger', name:'斯塔万格', country:'NORWAY', lon:5.73, lat:58.97, isCapital:false },
    { id:'drammen', name:'德拉门', country:'NORWAY', lon:10.20, lat:59.74, isCapital:false },
    { id:'stockholm', name:'斯德哥尔摩', country:'SWEDEN', lon:18.07, lat:59.33, isCapital:true },
    { id:'gothenburg', name:'哥德堡', country:'SWEDEN', lon:11.97, lat:57.71, isCapital:false },
    { id:'malmo', name:'马尔默', country:'SWEDEN', lon:13.00, lat:55.60, isCapital:false },
    { id:'kiruna', name:'基律纳', country:'SWEDEN', lon:20.23, lat:67.86, isCapital:false },
    { id:'uppsala', name:'乌普萨拉', country:'SWEDEN', lon:17.64, lat:59.86, isCapital:false },
    { id:'linkoping', name:'林雪平', country:'SWEDEN', lon:15.63, lat:58.41, isCapital:false },
    { id:'orebro', name:'厄勒布鲁', country:'SWEDEN', lon:15.21, lat:59.27, isCapital:false },
    { id:'breslau', name:'布雷斯劳', country:'GERMANY', lon:17.03, lat:51.11, isCapital:false },
    { id:'allestein', name:'阿伦施泰因', country:'GERMANY', lon:20.23, lat:53.76, isCapital:false },
    { id:'tilsit', name:'蒂尔西特', country:'GERMANY', lon:21.88, lat:55.09, isCapital:false },
    { id:'insterburg', name:'因斯特堡', country:'GERMANY', lon:21.15, lat:54.63, isCapital:false },
    { id:'loetzen', name:'勒岑', country:'GERMANY', lon:21.75, lat:53.99, isCapital:false },
    { id:'osterode', name:'奥斯特罗德', country:'GERMANY', lon:20.00, lat:53.42, isCapital:false },
    { id:'soldau', name:'索尔达乌', country:'GERMANY', lon:20.18, lat:53.23, isCapital:false },
    { id:'thorn', name:'托伦', country:'GERMANY', lon:18.60, lat:53.01, isCapital:false },
    { id:'bydgoszcz', name:'布龙贝格', country:'GERMANY', lon:17.93, lat:53.13, isCapital:false },
    { id:'graudenz', name:'格劳登茨', country:'GERMANY', lon:18.76, lat:53.49, isCapital:false },
    { id:'elbing', name:'埃尔宾', country:'GERMANY', lon:19.40, lat:54.16, isCapital:false },
    { id:'magdeburg', name:'马格德堡', country:'GERMANY', lon:11.63, lat:52.13, isCapital:false },
    { id:'halle', name:'哈勒', country:'GERMANY', lon:11.97, lat:51.48, isCapital:false },
    { id:'braunschweig', name:'不伦瑞克', country:'GERMANY', lon:10.53, lat:52.27, isCapital:false },
    { id:'essen', name:'埃森', country:'GERMANY', lon:7.01, lat:51.46, isCapital:false },
    { id:'duesseldorf', name:'杜塞尔多夫', country:'GERMANY', lon:6.78, lat:51.23, isCapital:false },
    { id:'bonn', name:'波恩', country:'GERMANY', lon:7.10, lat:50.73, isCapital:false },
    { id:'kassel', name:'卡塞尔', country:'GERMANY', lon:9.48, lat:51.31, isCapital:false },
    { id:'goettingen', name:'哥廷根', country:'GERMANY', lon:9.94, lat:51.54, isCapital:false },
    { id:'jena', name:'耶拿', country:'GERMANY', lon:11.59, lat:50.93, isCapital:false },
    { id:'erfurt', name:'埃尔福特', country:'GERMANY', lon:11.03, lat:50.98, isCapital:false },
    { id:'rostock', name:'罗斯托克', country:'GERMANY', lon:12.13, lat:54.09, isCapital:false },
    { id:'luebeck', name:'吕贝克', country:'GERMANY', lon:10.69, lat:53.87, isCapital:false },
    { id:'schwerin', name:'什未林', country:'GERMANY', lon:11.42, lat:53.64, isCapital:false },
    { id:'augsburg', name:'奥格斯堡', country:'GERMANY', lon:10.90, lat:48.37, isCapital:false },
    { id:'regensburg', name:'雷根斯堡', country:'GERMANY', lon:12.10, lat:49.02, isCapital:false },
    { id:'passau', name:'帕绍', country:'GERMANY', lon:13.47, lat:48.57, isCapital:false },
    { id:'wuerzburg', name:'维尔茨堡', country:'GERMANY', lon:9.95, lat:49.79, isCapital:false },
    { id:'bamberg', name:'班贝格', country:'GERMANY', lon:10.89, lat:49.90, isCapital:false },
    { id:'chemnitz', name:'开姆尼茨', country:'GERMANY', lon:12.92, lat:50.83, isCapital:false },
    { id:'freiburg', name:'弗赖堡', country:'GERMANY', lon:7.85, lat:47.99, isCapital:false },
    { id:'heidelberg', name:'海德堡', country:'GERMANY', lon:8.69, lat:49.40, isCapital:false },
    { id:'potsdam', name:'波茨坦', country:'GERMANY', lon:13.07, lat:52.40, isCapital:false },
    { id:'wittenberg', name:'维滕贝格', country:'GERMANY', lon:12.65, lat:51.87, isCapital:false },
    { id:'dessau', name:'德绍', country:'GERMANY', lon:12.24, lat:51.84, isCapital:false },
    { id:'gelsenkirchen', name:'盖尔森基兴', country:'GERMANY', lon:7.10, lat:51.52, isCapital:false },
    { id:'bochum', name:'波鸿', country:'GERMANY', lon:7.21, lat:51.48, isCapital:false },
    { id:'duisburg', name:'杜伊斯堡', country:'GERMANY', lon:6.76, lat:51.43, isCapital:false },
    { id:'krefeld', name:'克雷费尔德', country:'GERMANY', lon:6.57, lat:51.34, isCapital:false },
    { id:'bielefeld', name:'比勒费尔德', country:'GERMANY', lon:8.53, lat:52.02, isCapital:false },
    { id:'osnabrueck', name:'奥斯纳布吕克', country:'GERMANY', lon:8.05, lat:52.28, isCapital:false },
    { id:'oldenburg', name:'奥尔登堡', country:'GERMANY', lon:8.21, lat:53.14, isCapital:false },
    { id:'flensburg', name:'弗伦斯堡', country:'GERMANY', lon:9.44, lat:54.79, isCapital:false },
    { id:'limoges', name:'利摩日', country:'FRANCE', lon:1.26, lat:45.83, isCapital:false },
    { id:'clermont', name:'克莱蒙费朗', country:'FRANCE', lon:3.08, lat:45.78, isCapital:false },
    { id:'st_etienne', name:'圣埃蒂安', country:'FRANCE', lon:4.39, lat:45.44, isCapital:false },
    { id:'grenoble_fr', name:'格勒诺布尔', country:'FRANCE', lon:5.72, lat:45.19, isCapital:false },
    { id:'perpignan', name:'佩皮尼昂', country:'FRANCE', lon:2.90, lat:42.70, isCapital:false },
    { id:'caen', name:'卡昂', country:'FRANCE', lon:-0.37, lat:49.18, isCapital:false },
    { id:'rennes', name:'雷恩', country:'FRANCE', lon:-1.68, lat:48.11, isCapital:false },
    { id:'orleans_fr', name:'奥尔良', country:'FRANCE', lon:1.90, lat:47.90, isCapital:false },
    { id:'chartres', name:'沙特尔', country:'FRANCE', lon:1.49, lat:48.45, isCapital:false },
    { id:'valence_fr', name:'瓦朗斯', country:'FRANCE', lon:4.89, lat:44.93, isCapital:false },
    { id:'ajaccio', name:'阿雅克肖', country:'FRANCE', lon:8.74, lat:41.93, isCapital:false },
    { id:'pau', name:'波城', country:'FRANCE', lon:-0.37, lat:43.30, isCapital:false },
    { id:'bourges', name:'布尔日', country:'FRANCE', lon:2.40, lat:47.08, isCapital:false },
    { id:'auxerre', name:'欧塞尔', country:'FRANCE', lon:3.57, lat:47.80, isCapital:false },
    { id:'melun', name:'默伦', country:'FRANCE', lon:2.66, lat:48.54, isCapital:false },
    { id:'sens', name:'桑斯', country:'FRANCE', lon:3.28, lat:48.20, isCapital:false },
    { id:'mogilev', name:'莫吉廖夫', country:'RUSSIA', lon:30.34, lat:53.90, isCapital:false },
    { id:'gomel', name:'戈梅利', country:'RUSSIA', lon:30.98, lat:52.43, isCapital:false },
    { id:'chernigov', name:'切尔尼戈夫', country:'RUSSIA', lon:31.30, lat:51.50, isCapital:false },
    { id:'poltava', name:'波尔塔瓦', country:'RUSSIA', lon:34.57, lat:49.59, isCapital:false },
    { id:'kharkov', name:'哈尔科夫', country:'RUSSIA', lon:36.23, lat:49.99, isCapital:false },
    { id:'ekaterinoslav', name:'叶卡捷琳诺斯拉夫', country:'RUSSIA', lon:35.04, lat:48.46, isCapital:false },
    { id:'lugansk', name:'卢甘斯克', country:'RUSSIA', lon:39.31, lat:48.57, isCapital:false },
    { id:'rostov', name:'罗斯托夫', country:'RUSSIA', lon:39.72, lat:47.24, isCapital:false },
    { id:'tsaritsyn', name:'察里津', country:'RUSSIA', lon:44.38, lat:48.71, isCapital:false },
    { id:'astrakhan', name:'阿斯特拉罕', country:'RUSSIA', lon:48.03, lat:46.35, isCapital:false },
    { id:'smolensk', name:'斯摩棱斯克', country:'RUSSIA', lon:32.05, lat:54.78, isCapital:false },
    { id:'bryansk', name:'布良斯克', country:'RUSSIA', lon:34.39, lat:53.25, isCapital:false },
    { id:'orel', name:'奥廖尔', country:'RUSSIA', lon:36.08, lat:52.97, isCapital:false },
    { id:'kursk', name:'库尔斯克', country:'RUSSIA', lon:36.19, lat:51.71, isCapital:false },
    { id:'voronezh', name:'沃罗涅日', country:'RUSSIA', lon:39.21, lat:51.67, isCapital:false },
    { id:'tambov', name:'坦波夫', country:'RUSSIA', lon:41.40, lat:52.73, isCapital:false },
    { id:'penza', name:'奔萨', country:'RUSSIA', lon:45.01, lat:53.20, isCapital:false },
    { id:'saratov', name:'萨拉托夫', country:'RUSSIA', lon:46.03, lat:51.53, isCapital:false },
    { id:'kaluga', name:'卡卢加', country:'RUSSIA', lon:36.26, lat:54.53, isCapital:false },
    { id:'tver', name:'特维尔', country:'RUSSIA', lon:35.92, lat:56.86, isCapital:false },
    { id:'yaroslavl', name:'雅罗斯拉夫尔', country:'RUSSIA', lon:39.87, lat:57.63, isCapital:false },
    { id:'kostroma', name:'科斯特罗马', country:'RUSSIA', lon:40.93, lat:57.77, isCapital:false },
    { id:'vladimir', name:'弗拉基米尔', country:'RUSSIA', lon:40.41, lat:56.13, isCapital:false },
    { id:'ryazan', name:'梁赞', country:'RUSSIA', lon:39.73, lat:54.63, isCapital:false },
    { id:'novgorod', name:'诺夫哥罗德', country:'RUSSIA', lon:31.27, lat:58.52, isCapital:false },
    { id:'pskov', name:'普斯科夫', country:'RUSSIA', lon:28.33, lat:57.81, isCapital:false },
    { id:'dvinsk', name:'德文斯克', country:'RUSSIA', lon:26.53, lat:55.87, isCapital:false },
    { id:'vitebsk', name:'维捷布斯克', country:'RUSSIA', lon:30.22, lat:55.19, isCapital:false },
    { id:'nizhny', name:'下诺夫哥罗德', country:'RUSSIA', lon:43.93, lat:56.33, isCapital:false },
    { id:'kazan', name:'喀山', country:'RUSSIA', lon:49.11, lat:55.80, isCapital:false },
    { id:'ufa', name:'乌法', country:'RUSSIA', lon:55.97, lat:54.74, isCapital:false },
    { id:'orenburg', name:'奥伦堡', country:'RUSSIA', lon:55.10, lat:51.77, isCapital:false },
    { id:'perm', name:'彼尔姆', country:'RUSSIA', lon:56.25, lat:58.01, isCapital:false },
    { id:'ekaterinburg', name:'叶卡捷琳堡', country:'RUSSIA', lon:60.60, lat:56.84, isCapital:false },
    { id:'chelyabinsk', name:'车里雅宾斯克', country:'RUSSIA', lon:61.40, lat:55.16, isCapital:false },
    { id:'omsk', name:'鄂木斯克', country:'RUSSIA', lon:73.37, lat:54.99, isCapital:false },
    { id:'innsbruck', name:'因斯布鲁克', country:'AUSTRIA_HUNGARY', lon:11.39, lat:47.27, isCapital:false },
    { id:'bregenz', name:'布雷根茨', country:'AUSTRIA_HUNGARY', lon:9.75, lat:47.50, isCapital:false },
    { id:'klagenfurt', name:'克拉根福特', country:'AUSTRIA_HUNGARY', lon:14.31, lat:46.62, isCapital:false },
    { id:'villach', name:'菲拉赫', country:'AUSTRIA_HUNGARY', lon:13.85, lat:46.61, isCapital:false },
    { id:'leoben', name:'莱奥本', country:'AUSTRIA_HUNGARY', lon:15.10, lat:47.38, isCapital:false },
    { id:'steyr', name:'施泰尔', country:'AUSTRIA_HUNGARY', lon:14.42, lat:48.04, isCapital:false },
    { id:'wiener_neustadt', name:'维也纳新城', country:'AUSTRIA_HUNGARY', lon:16.25, lat:47.82, isCapital:false },
    { id:'eisenstadt', name:'艾森施塔特', country:'AUSTRIA_HUNGARY', lon:16.52, lat:47.85, isCapital:false },
    { id:'szombathely', name:'松博特海伊', country:'AUSTRIA_HUNGARY', lon:16.62, lat:47.23, isCapital:false },
    { id:'gyor', name:'杰尔', country:'AUSTRIA_HUNGARY', lon:17.63, lat:47.69, isCapital:false },
    { id:'sopron', name:'肖普朗', country:'AUSTRIA_HUNGARY', lon:16.59, lat:47.69, isCapital:false },
    { id:'debrecen', name:'德布勒森', country:'AUSTRIA_HUNGARY', lon:21.63, lat:47.53, isCapital:false },
    { id:'szeged', name:'塞格德', country:'AUSTRIA_HUNGARY', lon:20.15, lat:46.25, isCapital:false },
    { id:'pecs', name:'佩奇', country:'AUSTRIA_HUNGARY', lon:18.23, lat:46.07, isCapital:false },
    { id:'miskolc', name:'米什科尔茨', country:'AUSTRIA_HUNGARY', lon:20.78, lat:48.10, isCapital:false },
    { id:'kassa', name:'科希策', country:'AUSTRIA_HUNGARY', lon:21.26, lat:48.72, isCapital:false },
    { id:'arad', name:'阿拉德', country:'AUSTRIA_HUNGARY', lon:21.32, lat:46.17, isCapital:false },
    { id:'klausenburg', name:'克卢日', country:'AUSTRIA_HUNGARY', lon:23.60, lat:46.77, isCapital:false },
    { id:'brasso', name:'布拉索夫', country:'AUSTRIA_HUNGARY', lon:25.60, lat:45.65, isCapital:false },
    { id:'temesvar', name:'蒂米什瓦拉', country:'AUSTRIA_HUNGARY', lon:21.23, lat:45.75, isCapital:false },
    { id:'brunn', name:'布尔诺', country:'AUSTRIA_HUNGARY', lon:16.61, lat:49.20, isCapital:false },
    { id:'olmuetz', name:'奥洛穆茨', country:'AUSTRIA_HUNGARY', lon:17.25, lat:49.59, isCapital:false },
    { id:'teschen', name:'切欣', country:'AUSTRIA_HUNGARY', lon:18.62, lat:49.75, isCapital:false },
    { id:'iglau', name:'伊格劳', country:'AUSTRIA_HUNGARY', lon:15.59, lat:49.40, isCapital:false },
    { id:'znaim', name:'兹诺伊莫', country:'AUSTRIA_HUNGARY', lon:16.05, lat:48.86, isCapital:false },
    { id:'laibach', name:'莱巴赫(卢布尔雅那)', country:'AUSTRIA_HUNGARY', lon:14.51, lat:46.05, isCapital:false },
    { id:'pola', name:'波拉(普拉)', country:'AUSTRIA_HUNGARY', lon:13.85, lat:44.87, isCapital:false },
    { id:'fiume', name:'阜姆(里耶卡)', country:'AUSTRIA_HUNGARY', lon:14.44, lat:45.34, isCapital:false },
    { id:'esseg', name:'埃塞格(奥西耶克)', country:'AUSTRIA_HUNGARY', lon:18.69, lat:45.56, isCapital:false },
    { id:'peterwardein', name:'彼得罗瓦拉丁', country:'AUSTRIA_HUNGARY', lon:19.85, lat:45.20, isCapital:false },
    { id:'marburg', name:'马尔堡(马里博尔)', country:'AUSTRIA_HUNGARY', lon:15.65, lat:46.55, isCapital:false },
    { id:'bielitz', name:'别尔斯科', country:'AUSTRIA_HUNGARY', lon:19.05, lat:49.83, isCapital:false },
    { id:'pressburg2', name:'普雷斯堡', country:'AUSTRIA_HUNGARY', lon:17.11, lat:48.15, isCapital:false },
    { id:'hainburg', name:'海恩堡', country:'AUSTRIA_HUNGARY', lon:16.95, lat:48.14, isCapital:false },
    { id:'kremsier', name:'克雷姆西尔', country:'AUSTRIA_HUNGARY', lon:17.39, lat:49.40, isCapital:false },
    { id:'brescia', name:'布雷西亚', country:'ITALY', lon:10.21, lat:45.54, isCapital:false },
    { id:'bergamo', name:'贝加莫', country:'ITALY', lon:9.67, lat:45.70, isCapital:false },
    { id:'como', name:'科莫', country:'ITALY', lon:9.08, lat:45.81, isCapital:false },
    { id:'pavia', name:'帕维亚', country:'ITALY', lon:9.16, lat:45.19, isCapital:false },
    { id:'alessandria', name:'亚历山德里亚', country:'ITALY', lon:8.62, lat:44.91, isCapital:false },
    { id:'savona', name:'萨沃纳', country:'ITALY', lon:8.48, lat:44.31, isCapital:false },
    { id:'la_spezia', name:'拉斯佩齐亚', country:'ITALY', lon:9.87, lat:44.11, isCapital:false },
    { id:'livorno', name:'里窝那', country:'ITALY', lon:10.31, lat:43.55, isCapital:false },
    { id:'pisa', name:'比萨', country:'ITALY', lon:10.40, lat:43.72, isCapital:false },
    { id:'siena', name:'锡耶纳', country:'ITALY', lon:11.33, lat:43.32, isCapital:false },
    { id:'perugia', name:'佩鲁贾', country:'ITALY', lon:12.39, lat:43.11, isCapital:false },
    { id:'foggia', name:'福贾', country:'ITALY', lon:15.55, lat:41.46, isCapital:false },
    { id:'lecce', name:'莱切', country:'ITALY', lon:18.17, lat:40.35, isCapital:false },
    { id:'brindisi', name:'布林迪西', country:'ITALY', lon:17.94, lat:40.63, isCapital:false },
    { id:'cosenza', name:'科森扎', country:'ITALY', lon:16.25, lat:39.29, isCapital:false },
    { id:'reggio', name:'雷焦卡拉布里亚', country:'ITALY', lon:15.65, lat:38.11, isCapital:false },
    { id:'messina', name:'墨西拿', country:'ITALY', lon:15.55, lat:38.19, isCapital:false },
    { id:'syracuse', name:'锡拉库萨', country:'ITALY', lon:15.29, lat:37.08, isCapital:false },
    { id:'campobasso', name:'坎波巴索', country:'ITALY', lon:14.66, lat:41.56, isCapital:false },
    { id:'aosta', name:'奥斯塔', country:'ITALY', lon:7.32, lat:45.74, isCapital:false },
    { id:'newcastle', name:'纽卡斯尔', country:'UK', lon:-1.61, lat:54.97, isCapital:false },
    { id:'sheffield', name:'谢菲尔德', country:'UK', lon:-1.47, lat:53.38, isCapital:false },
    { id:'nottingham', name:'诺丁汉', country:'UK', lon:-1.15, lat:52.95, isCapital:false },
    { id:'cambridge', name:'剑桥', country:'UK', lon:0.12, lat:52.21, isCapital:false },
    { id:'brighton', name:'布莱顿', country:'UK', lon:-0.14, lat:50.82, isCapital:false },
    { id:'exeter', name:'埃克塞特', country:'UK', lon:-3.53, lat:50.72, isCapital:false },
    { id:'inverness', name:'因弗内斯', country:'UK', lon:-4.22, lat:57.48, isCapital:false }
];

// ============================================================
//  海洋节点 — 位于海洋中，以国家名命名
// ============================================================
const NAVAL_BASES = [
  {
    "id": "nb_ger_1",
    "country": "GERMANY",
    "lon": 5.5,
    "lat": 56.2,
    "name": "德国海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_ger_2",
    "country": "GERMANY",
    "lon": 8,
    "lat": 55.9,
    "name": "德国海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_ger_3",
    "country": "GERMANY",
    "lon": 13.5,
    "lat": 55.3,
    "name": "德国海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_ger_4",
    "country": "GERMANY",
    "lon": 17,
    "lat": 55.5,
    "name": "德国海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_uk_1",
    "country": "UK",
    "lon": -3,
    "lat": 58,
    "name": "英国海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_uk_2",
    "country": "UK",
    "lon": 2,
    "lat": 53,
    "name": "英国海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_uk_3",
    "country": "UK",
    "lon": -8,
    "lat": 51,
    "name": "英国海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_uk_4",
    "country": "UK",
    "lon": -0.5,
    "lat": 50,
    "name": "英国海洋节点",
    "region": "english_channel"
  },
  {
    "id": "nb_uk_5",
    "country": "UK",
    "lon": -10,
    "lat": 54,
    "name": "英国海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_fra_1",
    "country": "FRANCE",
    "lon": -5.5,
    "lat": 46.5,
    "name": "法国海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_fra_2",
    "country": "FRANCE",
    "lon": -0.5,
    "lat": 49.8,
    "name": "法国海洋节点",
    "region": "english_channel"
  },
  {
    "id": "nb_fra_3",
    "country": "FRANCE",
    "lon": 6.5,
    "lat": 41.5,
    "name": "法国海洋节点",
    "region": "mediterranean"
  },
  {
    "id": "nb_ita_1",
    "country": "ITALY",
    "lon": 13,
    "lat": 39.5,
    "name": "意大利海洋节点",
    "region": "mediterranean"
  },
  {
    "id": "nb_ita_2",
    "country": "ITALY",
    "lon": 17.5,
    "lat": 41,
    "name": "意大利海洋节点",
    "region": "adriatic"
  },
  {
    "id": "nb_ita_3",
    "country": "ITALY",
    "lon": 14,
    "lat": 37.5,
    "name": "意大利海洋节点",
    "region": "mediterranean"
  },
  {
    "id": "nb_rus_1",
    "country": "RUSSIA",
    "lon": 21.5,
    "lat": 60.5,
    "name": "俄国海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_rus_2",
    "country": "RUSSIA",
    "lon": 33,
    "lat": 42.5,
    "name": "俄国海洋节点",
    "region": "black_sea"
  },
  {
    "id": "nb_rus_3",
    "country": "RUSSIA",
    "lon": 36.5,
    "lat": 44,
    "name": "俄国海洋节点",
    "region": "black_sea"
  },
  {
    "id": "nb_rus_4",
    "country": "RUSSIA",
    "lon": 132.5,
    "lat": 42.5,
    "name": "俄国海洋节点",
    "region": "pacific"
  },
  {
    "id": "nb_ah_1",
    "country": "AUSTRIA_HUNGARY",
    "lon": 17,
    "lat": 42.5,
    "name": "奥匈海洋节点",
    "region": "adriatic"
  },
  {
    "id": "nb_tur_1",
    "country": "TURKEY",
    "lon": 24,
    "lat": 37.5,
    "name": "土耳其海洋节点",
    "region": "aegean"
  },
  {
    "id": "nb_tur_2",
    "country": "TURKEY",
    "lon": 33,
    "lat": 42.5,
    "name": "土耳其海洋节点",
    "region": "black_sea"
  },
  {
    "id": "nb_tur_3",
    "country": "TURKEY",
    "lon": 30,
    "lat": 34.5,
    "name": "土耳其海洋节点",
    "region": "mediterranean"
  },
  {
    "id": "nb_spa_1",
    "country": "SPAIN",
    "lon": -11,
    "lat": 42.5,
    "name": "西班牙海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_spa_2",
    "country": "SPAIN",
    "lon": 2,
    "lat": 38.5,
    "name": "西班牙海洋节点",
    "region": "mediterranean"
  },
  {
    "id": "nb_ned_1",
    "country": "NETHERLANDS",
    "lon": 3.5,
    "lat": 52,
    "name": "荷兰海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_por_1",
    "country": "PORTUGAL",
    "lon": -12,
    "lat": 38,
    "name": "葡萄牙海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_dan_1",
    "country": "DENMARK",
    "lon": 7.5,
    "lat": 57,
    "name": "丹麦海洋节点",
    "region": "north_sea"
  },
  {
    "id": "nb_dan_2",
    "country": "DENMARK",
    "lon": 16,
    "lat": 55,
    "name": "丹麦海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_rom_1",
    "country": "ROMANIA",
    "lon": 31,
    "lat": 43,
    "name": "罗马尼亚海洋节点",
    "region": "black_sea"
  },
  {
    "id": "nb_nor_1",
    "country": "NORWAY",
    "lon": 4,
    "lat": 62,
    "name": "挪威海洋节点",
    "region": "atlantic"
  },
  {
    "id": "nb_nor_2",
    "country": "NORWAY",
    "lon": 10,
    "lat": 68,
    "name": "挪威海洋节点",
    "region": "arctic"
  },
  {
    "id": "nb_swe_1",
    "country": "SWEDEN",
    "lon": 19.5,
    "lat": 58,
    "name": "瑞典海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_fin_1",
    "country": "FINLAND",
    "lon": 24.5,
    "lat": 60,
    "name": "芬兰海洋节点",
    "region": "baltic"
  },
  {
    "id": "nb_gre_1",
    "country": "GREECE",
    "lon": 25,
    "lat": 36,
    "name": "希腊海洋节点",
    "region": "aegean"
  }
];
