// ============================================================
//  Iron & Dominion 1914 — 预设铁路网（1914 全欧洲主干线）
//  粒度=城市对（城市为铁路节点），键为规范化的 cityA|cityB
//  归属动态判定：段两端城市 owner 为同一方可用，占领自动接管
//  覆盖：各国国内主干线 + 东方快车等跨境大动脉
// ============================================================

const PRESET_RAILWAYS = [
    // ===== 德意志 =====
    ['berlin', 'hamburg'],
    ['berlin', 'hannover'],
    ['hannover', 'cologne'],
    ['berlin', 'magdeburg'],
    ['magdeburg', 'hannover'],
    ['hamburg', 'bremen'],
    ['hamburg', 'kiel'],
    ['kiel', 'flensburg'],
    ['bremen', 'hannover'],
    ['berlin', 'leipzig'],
    ['leipzig', 'dresden'],
    ['berlin', 'breslau'],
    ['posen', 'breslau'],
    ['cologne', 'koblenz'],
    ['koblenz', 'mainz'],
    ['mainz', 'frankfurt'],
    ['cologne', 'frankfurt'],
    ['leipzig', 'nuremberg'],
    ['nuremberg', 'munich'],
    ['frankfurt', 'nuremberg'],
    ['frankfurt', 'stuttgart'],
    ['stuttgart', 'munich'],
    ['berlin', 'posen'],
    ['berlin', 'stettin'],
    ['posen', 'danzig'],
    ['danzig', 'konigsberg'],
    ['konigsberg', 'insterburg'],
    ['konigsberg', 'tilsit'],
    ['metz', 'saarbruecken'],
    ['saarbruecken', 'mainz'],
    ['strasbourg', 'karlsruhe'],
    ['karlsruhe', 'stuttgart'],
    // ===== 法国 =====
    ['paris', 'lille'],
    ['paris', 'amiens'],
    ['paris', 'reims'],
    ['reims', 'mezieres'],
    ['reims', 'verdun'],
    ['paris', 'verdun'],
    ['verdun', 'metz'],
    ['paris', 'nancy'],
    ['verdun', 'nancy'],
    ['nancy', 'strasbourg'],
    ['strasbourg', 'colmar'],
    ['paris', 'orleans_fr'],
    ['paris', 'dijon'],
    ['dijon', 'lyon'],
    ['paris', 'lyon'],
    ['lyon', 'marseille'],
    ['marseille', 'montpellier'],
    ['montpellier', 'toulouse'],
    ['lyon', 'nice'],
    ['paris', 'bordeaux'],
    ['bordeaux', 'toulouse'],
    ['paris', 'nantes'],
    ['nantes', 'brest'],
    ['paris', 'rouen'],
    ['lille', 'boulogne'],
    ['paris', 'tours'],
    // ===== 英国 =====
    ['london', 'birmingham'],
    ['london', 'bristol'],
    ['london', 'southampton'],
    ['london', 'york'],
    ['york', 'newcastle'],
    ['newcastle', 'edinburgh'],
    ['edinburgh', 'glasgow'],
    ['glasgow', 'aberdeen'],
    ['birmingham', 'liverpool'],
    ['liverpool', 'manchester'],
    ['manchester', 'leeds'],
    ['birmingham', 'sheffield'],
    ['london', 'norwich'],
    ['dublin', 'belfast'],
    ['dublin', 'cork'],
    // ===== 意大利 =====
    ['milan', 'turin'],
    ['milan', 'venice'],
    ['milan', 'genoa'],
    ['milan', 'bologna'],
    ['bologna', 'florence'],
    ['florence', 'rome'],
    ['rome', 'naples'],
    ['turin', 'genoa'],
    ['venice', 'trieste'],
    // ===== 西班牙 / 葡萄牙 =====
    ['madrid', 'zaragoza'],
    ['zaragoza', 'barcelona'],
    ['madrid', 'seville'],
    ['madrid', 'bilbao'],
    ['madrid', 'valencia_sp'],
    ['madrid', 'lisbon'],
    ['lisbon', 'coimbra'],
    ['coimbra', 'porto'],
    // ===== 荷兰 / 比利时 / 卢森堡 =====
    ['amsterdam', 'rotterdam'],
    ['amsterdam', 'utrecht'],
    ['rotterdam', 'thehague'],
    ['brussels', 'antwerp'],
    ['brussels', 'liege'],
    ['brussels', 'mons'],
    ['brussels', 'namur'],
    ['liege', 'luxembourg'],
    ['luxembourg', 'metz'],
    // ===== 瑞士 =====
    ['zurich', 'basel'],
    ['zurich', 'bern'],
    ['bern', 'geneva'],
    ['basel', 'strasbourg'],
    ['geneva', 'lyon'],
    ['geneva', 'dijon'],
    // ===== 丹麦 / 瑞典 / 挪威 / 芬兰 =====
    ['copenhagen', 'odense'],
    ['odense', 'aarhus'],
    ['aarhus', 'aalborg'],
    ['flensburg', 'aarhus'],
    ['stockholm', 'gothenburg'],
    ['gothenburg', 'malmo'],
    ['stockholm', 'uppsala'],
    ['oslo', 'gothenburg'],
    ['oslo', 'stockholm'],
    ['oslo', 'bergen'],
    ['oslo', 'drammen'],
    ['helsinkifi', 'turku'],
    ['helsinkifi', 'tampere'],
    ['helsinkifi', 'viipuri'],
    ['viipuri', 'saint_petersburg'],
    // ===== 俄国（欧俄主干） =====
    ['saint_petersburg', 'moscow'],
    ['saint_petersburg', 'riga'],
    ['moscow', 'smolensk'],
    ['smolensk', 'minsk'],
    ['minsk', 'warsaw'],
    ['moscow', 'kiev'],
    ['kiev', 'odessa'],
    ['kiev', 'warsaw'],
    ['riga', 'warsaw'],
    ['moscow', 'rostov'],
    // ===== 奥匈 =====
    ['vienna', 'budapest'],
    ['vienna', 'prague'],
    ['vienna', 'linz'],
    ['linz', 'salzburg_ah'],
    ['vienna', 'graz'],
    ['graz', 'laibach'],
    ['laibach', 'trieste'],
    ['budapest', 'zagreb'],
    ['zagreb', 'sarajevo'],
    ['budapest', 'kassa'],
    ['kassa', 'lemberg'],
    ['budapest', 'brasso'],
    ['vienna', 'brunn'],
    ['brunn', 'krakow'],
    ['krakow', 'lemberg'],
    ['krakow', 'warsaw'],
    ['vienna', 'innsbruck'],
    ['prague', 'brunn'],
    // ===== 巴尔干 / 土耳其 / 希腊 =====
    ['belgrade', 'nis'],
    ['belgrade', 'budapest'],
    ['nis', 'thessaloniki'],
    ['thessaloniki', 'athens'],
    ['sofia', 'nis'],
    ['sofia', 'plovdiv'],
    ['plovdiv', 'varna'],
    ['bucharest', 'constanta'],
    ['bucharest', 'iasi'],
    ['bucharest', 'brasov'],
    ['brasso', 'bucharest'],
    ['thessaloniki', 'istanbul'],
    ['plovdiv', 'istanbul'],
    ['istanbul', 'ankara'],
    ['istanbul', 'izmir'],
    // ===== 跨境大动脉 =====
    // 施里芬线：列日-亚琛 / 蒙斯-里尔
    ['liege', 'aachen'],
    ['mons', 'lille'],
    // 中欧：萨尔茨堡-慕尼黑 / 布伦纳山口 / 苏黎世-慕尼黑
    ['salzburg_ah', 'munich'],
    ['innsbruck', 'munich'],
    ['zurich', 'munich'],
    // 圣哥达：巴塞尔-米兰
    ['basel', 'milan'],
    // 东线：柏林-华沙已由波森/但泽覆盖；华沙-维也纳经克拉科夫
    // 西地中海：巴塞罗那-佩皮尼昂
    ['barcelona', 'perpignan'],
];
